DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS readings;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE readings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    co2 INTEGER,
    temperature REAL,
    humidity REAL,
    time DATETIME DEFAULT CURRENT_TIMESTAMP
);